### ISSUE TITLE
Compatibility with Luminator display?

### ISSUE THREAD

**Issue by EdwardDeaver** [CarlRaymond/AnnaxFlipdotDriver#1]
Hi,

This is incredible work. Do you know if your driver board will work with Luminator displays? 

Like this https://www.ebay.com/itm/144216620709?hash=item2193fafea5:g:N0wAAOSwDvphTfJC

Or this https://www.ebay.com/itm/193406265045?hash=item2d07e966d5:g:k~gAAOSwfqJgx9sI

**Comment by CarlRaymond** [comment]
Edward, it's not plug-compatible for sure. My panel has two connectors, and the project has a circuit board for each one. The Luminator panel has a single connector, and so won't work at that level. Electrically it may work fine, if the panel is constructed the same way, and the row and column lines are brought out to that connector, and it has the steering diodes on board. But that's not a sure thing. So I'm afraid it's no help with that board.

That's the problem with these things. They are quite rare now, and they're not all identical. I'd like to get a couple more panels like I have, but I can't find them. Good luck!
